data = [
    {'name': 'Justin Bieber','follower_count': 133,'description': 'Musician','country': 'Canada'},
    {'name': 'Zendaya','follower_count': 68,'description': 'Actress and musician','country': 'United States'},

    {'name': 'David Beckham','follower_count': 82,'description': 'Footballer','country': 'United Kingdom'},
    {'name': 'Khloé Kardashian','follower_count': 108,'description': 'Reality TV personality and businesswoman','country': 'United States'},
    {'name': 'Shawn Mendes','follower_count': 57,'description': 'Musician','country': 'Canada'},
    {'name': 'Rihanna','follower_count': 81,'description': 'Musician and businesswoman','country': 'Barbados'},
    {'name': 'Kourtney Kardashian','follower_count': 90,'description': 'Reality TV personality','country': 'United States'},
    {'name': 'Miley Cyrus','follower_count': 107,'description': 'Musician and actress','country': 'United States'},
    {'name': 'Selena Gomez','follower_count': 174,'description': 'Musician and actress','country': 'United States'},
    {'name': 'Kylie Jenner','follower_count': 172,'description': 'Reality TV personality and businesswoman and Self-Made Billionaire','country': 'United States'},
    {'name': 'Demi Lovato','follower_count': 80,'description': 'Musician and actress','country': 'United States'},
    {'name': 'Cristiano Ronaldo','follower_count': 215,'description': 'Footballer','country': 'Portugal'},
    {'name': 'Ellen DeGeneres','follower_count': 87,'description': 'Comedian','country': 'United States'},
    {'name': 'Kendall Jenner','follower_count': 127,'description': 'Reality TV personality and Model','country': 'United States'},
    {'name': 'Billie Eilish','follower_count': 61,'description': 'Musician','country': 'United States'},
    {'name': 'National Geographic','follower_count': 135,'description': 'Magazine','country': 'United States'},
    {'name': 'Dwayne Johnson','follower_count': 181,'description': 'Actor and professional wrestler','country': 'United States'},
    {'name': 'Justin Timberlake','follower_count': 59,'description': 'Musician and actor','country': 'United States'},
    {'name': 'Nicki Minaj','follower_count': 113,'description': 'Musician','country': 'Trinidad and Tobago'},
    {'name': 'Katy Perry','follower_count': 94,'description': 'Musician','country': 'United States'},
    {'name': 'Camila Cabello','follower_count': 49,'description': 'Musician','country': 'Cuba'},
    {'name': 'Priyanka Chopra Jonas','follower_count': 53,'description': 'Actress and musician','country': 'India'},
    {'name': 'Nike','follower_count': 109,'description': 'Sportswear multinational','country': 'United States'},
    {'name': 'Shakira','follower_count': 66,'description': 'Musician','country': 'Colombia'},
    {'name': 'Instagram','follower_count': 346,'description': 'Social media platform','country': 'United States'},
    {'name': 'Beyoncé','follower_count': 145,'description': 'Musician','country': 'United States'},
    {'name': 'FC Barcelona','follower_count': 85,'description': 'Football club','country': 'Spain'},
    {'name': 'LeBron James','follower_count': 63,'description': 'Basketball player','country': 'United States'},
    {'name': '9GAG','follower_count': 52,'description': 'Social media platform','country': 'China'},
    {'name': 'Ronaldo','follower_count': 51,'description': 'Footballer','country': 'Brasil'},
    {'name': 'Emma Watson','follower_count': 56,'description': 'Actress','country': 'United Kingdom'},
    {'name': 'David Beckham','follower_count': 82,'description': 'Footballer','country': 'United Kingdom'},
    {'name': 'Demi Lovato','follower_count': 80,'description': 'Musician and actress','country': 'United States'},
    {'name': 'Kourtney Kardashian','follower_count': 90,'description': 'Reality TV personality','country': 'United States'},
    {'name': 'Kevin Hart','follower_count': 89,'description': 'Comedian and actor','country': 'United States'},
    {'name': 'Neymar','follower_count': 138,'description': 'Footballer','country': 'Brasil'},
    {'name': 'Lionel Messi','follower_count': 149,'description': 'Footballer','country': 'Argentina'},
    {'name': 'Victoria\'s Secret','follower_count': 69,'description': 'Lingerie brand','country': 'United States'},
    {'name': 'Gigi Hadid','follower_count': 54,'description': 'Model','country': 'United States'},
    {'name': 'Cardi B','follower_count': 67,'description': 'Musician','country': 'United States'},
    {'name': 'Shawn Mendes','follower_count': 57,'description': 'Musician','country': 'Canada'},
    {'name': 'NBA','follower_count': 47,'description': 'Club Basketball Competition','country': 'United States'},
    {'name': 'Justin Bieber','follower_count': 133,'description': 'Musician','country': 'Canada'},
    {'name': 'Taylor Swift','follower_count': 131,'description': 'Musician','country': 'United States'},
    {'name': 'Selena Gomez','follower_count': 174,'description': 'Musician and actress','country': 'United States'},
    {'name': 'Kylie Jenner','follower_count': 172,'description': 'Reality TV personality and businesswoman and Self-Made Billionaire','country': 'United States'},
    {'name': 'Khloé Kardashian','follower_count': 108,'description': 'Reality TV personality and businesswoman','country': 'United States'},
    {'name': 'Ariana Grande','follower_count': 183,'description': 'Musician and actress','country': 'United States'},

    {'name': 'Virat Kohli','follower_count': 55,'description': 'Cricketer','country': 'India'}
]
